### ISSUE TITLE
SenpaiEditiones : failed to fetch Chapters

### ISSUE THREAD

**Issue by danielblafer** [manga-download/haruneko#713] opened 2024-07-27 20:45 UTC
You get the complete list of chapters without problems, but when viewing/downloading the chapter you get “TypeError: Failed to fetch”.

I have noticed that the number of sheets/images is correct, maybe it is a problem handling the image individually.

![image](https://github.com/user-attachments/assets/c4ca05ef-2d96-473d-8f3d-f40e5f62758e)

**Comment by MikeZeDev** [comment] 2024-07-28 18:17
🤦‍♂️

**Comment by danielblafer** [comment] 2024-07-28 18:33
> Automated test are still valid . ![image](https://private-user-images.githubusercontent.com/10671518/352859370-92445983-4e2c-4c2c-970b-2caa43e2202c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTEzNDMsIm5iZiI6MTcyMjE5MTA0MywicGF0aCI6Ii8xMDY3MTUxOC8zNTI4NTkzNzAtOTI0NDU5ODMtNGUyYy00YzJjLTk3MGItMmNhYTQzZTIyMDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE4MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MzY4NGFhOTc2YTM4ZDYzMDIxMjkxYzNjMmRjNjliZWVjZjU3OWQ1MDliOThiOGU2MTJkYWUyNGJkZmE1MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YbWbJQ0LD9JosSnMX8FbjsrTlJVYKSMaBWtD4CiY6S8)
> 
> images from your selected chapter are loading fine
> 
> ![image](https://private-user-images.githubusercontent.com/10671518/352859507-5e411f25-add1-48c5-9812-cb5d30461bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTEzNDMsIm5iZiI6MTcyMjE5MTA0MywicGF0aCI6Ii8xMDY3MTUxOC8zNTI4NTk1MDctNWU0MTFmMjUtYWRkMS00OGM1LTk4MTItY2I1ZDMwNDYxYmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE4MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NDg2ZTdlYjc5NGU1NmVhODkxZTFlYjY1N2I5M2EwNjAyNDAwNmYxZDg2ZTdmOGVhNTUyNzg3ZTNjM2Q4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBtlpvpzLKj8GqFjl27shU-BiS3oMb6EUuzkTKHFCA4)



> Automated test are still valid . ![image](https://private-user-images.githubusercontent.com/10671518/352859370-92445983-4e2c-4c2c-970b-2caa43e2202c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTE3NjcsIm5iZiI6MTcyMjE5MTQ2NywicGF0aCI6Ii8xMDY3MTUxOC8zNTI4NTkzNzAtOTI0NDU5ODMtNGUyYy00YzJjLTk3MGItMmNhYTQzZTIyMDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE4MzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NGNmNWM1OGNhYjYxZmQ5MTQ4NDIyN2FmNzdjNjRmYTY3NWRkNjFlZjYwYzJhMzRkMjI4MTZlOWM3MzRlZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SSrdyUpEbX0rUj1gpitq04IPxgOOWinmFPoKOVVAWcc)
> 
> images from your selected chapter are loading fine
> 
> ![image](https://private-user-images.githubusercontent.com/10671518/352859507-5e411f25-add1-48c5-9812-cb5d30461bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTE3NjcsIm5iZiI6MTcyMjE5MTQ2NywicGF0aCI6Ii8xMDY3MTUxOC8zNTI4NTk1MDctNWU0MTFmMjUtYWRkMS00OGM1LTk4MTItY2I1ZDMwNDYxYmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE4MzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjFiOGZlYjljZTFhZDdkYWUzNzY4NWE4ODg5YzhhNzY5NmY3MzhhMDgxN2U0ZmNhYmE3NzU5NzJjMGNjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l17skxDF8lBPh_CYo3bCcGU-HRGtKiL-SAA93ofDxTk)

🤦‍♂️

**Comment by MikeZeDev** [comment] 2024-07-28 18:40
Same issue : https://github.com/manga-download/haruneko/issues/643

**Comment by danielblafer** [comment] 2024-07-28 18:46
> Same issue : #643

So, I understand that it is a general problem yet to be solved?

**Comment by MikeZeDev** [comment] 2024-07-28 18:51
An issue, yes. 
"To be solved", idk.

I mean, its 2024, website itself is using https but images are served using http, its bound to cause problems in real life browsers.
Chrome, Firefox, whatever may yell about mixed contents.

I'd' say its the website problem but its open to debate.

**Comment by danielblafer** [comment] 2024-07-28 19:00
I understand, although it seems strange to me, because this particular scan has the images in its root domain that is with https certificate, as well as serving them under the wordpress cdn.`https://i2.wp.com`

![image](https://github.com/user-attachments/assets/b639e970-aef8-4ad0-8d50-96206033288c)

![image](https://github.com/user-attachments/assets/71b5fa76-0f2e-48b9-af0b-e4b1041951e9)

maybe at some point in handling the image url string the https is being replaced by http ?

seeing as they use the wordpress cdn a dirty way to get around the problem of websites that use http is to pass the image through the cdn, as it accepts http and they display it in https.  🤔

**Comment by MikeZeDev** [comment] 2024-07-28 19:22
WordPress pictures are processed by Photon. we remove the ip.wp.com to get best image quality.

And thats where the problem is.
Meanwhile, i will issue a fix for this website.

**Closed** 2024-07-29 19:02 UTC
Labels: bug
