### ISSUE TITLE
Bug: 2-page spread not completely downloaded

### ISSUE THREAD

**Issue by noorhakim** [manga-download/haruneko#916] opened 2024-12-05 04:18 UTC
I try download comic with title "Something is Killing the Children" form ComicExtra or azcomix.me (now), when it comes to 2-page spread, it will not completely downloaded (it should be more wider than this). Like the image trim/crop two make it regular page.

I did check the web directly and when show 2-page spread it's looking fine.

Format: .pdf

Here some screenshot from comic i downloaded.
![image](https://github.com/user-attachments/assets/36b90b94-1542-4ac6-88c4-28f62d2def65)
![image](https://github.com/user-attachments/assets/c8bd5184-94d4-4245-a5c0-1022c66cba49)

**Comment by MikeZeDev** [comment] 2024-12-05 10:23
Its not a bug its designed like this. Images files are downloaded, then one file = one pdf page.  Its not possible to detect "double pages" at the file level. If you want more fine tuned pdf creation i am afraid you'd have download as pictures, and make a pdf yourself using external tools.

**Comment by noorhakim** [comment] 2024-12-05 13:11
I just hope its designed like hakuneko when downloaded to pdf.

**Comment by Sheepux** [comment] 2024-12-05 23:45
pdf is the worst format you would want for such case

**Comment by ronny1982** [comment] 2024-12-10 18:43
Works as designed ➔ `Won't Fix`

**Closed by ronny1982** 2024-12-10 18:43 UTC
